
van:
  name: sunho
  age: 30

spring:
  profiles:
    group:
      prod:
        - prod-age
        - prod-name
      beta:
        - beta-name
        - beta-age
  datasource:
    url: jdbc:postgresql://localhost:25432/kvp_springboot
    username: kvp-admin
    password: kvp-admin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
#    generate-ddl: true


#logging:
#  level:
#    aaaaaa: debug
server:
  port: 18081
