
van:
  name: sunho
  age: 30

spring:
  profiles:
    group:
      prod:
        - prod-age
        - prod-name
      beta:
        - beta-name
        - beta-age
  datasource:
    url: jdbc:mysql://localhost:23306/kvp_springboot
    username: kvp-admin
    password: kvp-admin

#logging:
#  level:
#    aaaaaa: debug
server:
  port: 18081
