version: '3.7'
services:
  kvp-mysql:
    container_name: kvp-mysql80
    image: mysql/mysql-server:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Seoul
    command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--lower_case_table_names=1"]
    ports:
      - "23306:3306"
    volumes:
      - ./mysql-init.d:/docker-entrypoint-initdb.d
  kvp-postgresql:
    container_name: kvp-postgresql142
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: kvp-admin
      POSTGRES_USER: kvp-admin
      POSTGRES_DB: kvp_springboot
    ports:
      - "25432:5432"
  kvp-adminer:
    image: adminer
    ports:
      - "28080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=kvp-mysql80
      - ADMINER_DESIGN=nette
      - ADMINER_PLUGINS=tables-filter tinymce