create table account
(
    id       int8 generated by default as identity,
    active   boolean not null,
    email    varchar(255),
    password varchar(255),
    username varchar(255),
    primary key (id)
);